<a href="https://colab.research.google.com/github/Aaryant31/linearRegression-Prac/blob/main/multivarite_linearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [144]:
#imprting Library
import pandas as pd
import numpy as np
from  sklearn import linear_model
import matplotlib.pyplot as plt
%matplotlib inline
import math

In [145]:
#install new package  

!pip install word2number

In [146]:
#importing the new installed package
from word2number import w2n 


In [147]:
#loading dataset
df=pd.read_csv("https://raw.githubusercontent.com/Aaryant31/linearRegression-Prac/main/hiring.csv")

In [148]:
df.head(10)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [149]:
#filling na value of exp as 0
df['experience']=df['experience'].fillna('zero')

In [150]:
df.head(10)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [151]:
#applying function to whole column
df.experience = df.experience.apply(w2n.word_to_num)

In [152]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [153]:
#filling na value of test_score as the median of tes score
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(df["test_score(out of 10)"].mean())

In [154]:
df['test_score(out of 10)']=df['test_score(out of 10)'].astype(int)

In [155]:
df.head(10)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                      8                           9      50000
1           0                      8                           6      45000
2           5                      6                           7      60000
3           2                     10                          10      65000
4           7                      9                           6      70000
5           3                      7                          10      62000
6          10                      7                           7      72000
7          11                      7                           8      80000

In [156]:
#droping dependent columns
new_df=df.drop('salary($)',axis=1)
new_df.head()

experience  test_score(out of 10)  interview_score(out of 10)
0           0                      8                           9
1           0                      8                           6
2           5                      6                           7
3           2                     10                          10
4           7                      9                           6

In [157]:
df["salary($)"]

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [158]:
#creating model of linear Regression
reg=linear_model.LinearRegression()
#fitting model to oue data
reg.fit(new_df,df["salary($)"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [159]:
#predicting
reg.predict([[2,9,6]])

array([53713.86677124])

In [160]:
#predicting
reg.predict([[12,10,10]])

array([93747.79628651])

In [161]:
#printing the slope
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [162]:
#printing the intercept
reg.intercept_

14992.65144669314